name=Basic
version=1.0.0
author=Realtek
maintainer=Realtek <realtek@example.com>
sentence=Basic examples for AmebaPro2
paragraph=Basic examples including LED blink, GPIO control, etc.
category=Examples
url=
architectures=AmebaPro2
